# Generated by Django 4.2.4 on 2023-09-03 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_news_alter_comment_post_delete_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='news',
        ),
        migrations.AddField(
            model_name='news',
            name='photo_one',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='photo_two',
            field=models.URLField(blank=True, null=True),
        ),
    ]
