# Generated by Django 4.2.4 on 2023-09-04 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_remove_category_slug_category_slugs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slugs',
        ),
    ]
