# Generated by Django 4.2.4 on 2023-09-06 11:45

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_alter_news_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, default='general', editable=True, populate_from='name', unique=True),
        ),
    ]
